CREATE TABLE IF NOT EXISTS departments (
                                           id integer generated by default as identity not null primary key,
                                           name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS patients (
                                        id integer generated by default as identity not null primary key,
                                        full_name VARCHAR(255) NOT NULL,
                                        age INT NOT NULL,
                                        gender VARCHAR(10) NOT NULL,
                                        department_id integer,
                                        FOREIGN KEY (department_id) REFERENCES departments(id)
);